[exp]
fps = 25
realdims = None
regions = True

[track]
startframe = 1
stopframe = 99999
keep_frames = 10
strict = False
overwrite = True
create_vid = True
create_dat = True
simple = True
orientfrombw = False
linkdistreshold = 100

[bgextract]
bg_frames = 10

[orient]
get = False
delwindow = 1
minvel = 4

[vis]
show_tracking = True
vid_displaysize = 1
frame_disstep = 10
waitkey = 1
idcol = None
contour_col = (255, 0, 0)
centre_col = (255, 255, 255)
centre_lwidth = 13
orient_col = (0, 0, 0)
orient_lwidth = 2
orient_tip = 0.15
orient_length = 15
traj_col = (0, 255, 255)
traj_length = 4
traj_minthick = 6.4
traj_maxthick = 9
traj_opacity = 0.5
mask_opacity = 0.15
box_opacity = 0.7
contnrs = False
trajs_below = False